Array Basics

In [1]:
#1D array


In [2]:
import numpy as np

In [3]:
my_list = [1,2,3,4,5]
print(my_list)

[1, 2, 3, 4, 5]


In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
#2D array

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy arrays using built in methods

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.linspace(0,5,10) #gives 10 evenly spaced points between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(5) #wil give a uniform distribution between 0 and 1 in 1D

array([0.10662404, 0.84288165, 0.05083725, 0.77715355, 0.31071622])

In [22]:
np.random.rand(4,4) #wil give a uniform distribution between 0 and 1 in 2D

array([[0.37000046, 0.80469912, 0.12981372, 0.88021405],
       [0.26564991, 0.99249345, 0.08048113, 0.47576841],
       [0.06451529, 0.02671156, 0.30973864, 0.13107231],
       [0.10012079, 0.41365517, 0.98849682, 0.72571533]])

In [24]:
np.random.randn(4) #this will give the gaussian/standard normal distribution in 1D

array([-0.75998019,  0.91395341,  0.43872312, -1.65719163])

In [28]:
np.random.randint(0,100) #generate random integer within the range

19

In [29]:
np.random.randint(0,100,10) #generate 10 random integer within the range

array([50, 49, 12, 65, 74, 21, 46, 26, 98, 47])

Useful attributes and methods

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ran_arr = np.random.randint(0,50,10)

In [36]:
ran_arr

array([ 5, 13, 11, 26, 45,  1, 30, 44, 41, 39])

In [37]:
ran_arr.max()

45

In [38]:
ran_arr.min()

1

In [39]:
ran_arr.argmax()

4

In [40]:
ran_arr.argmin()

5

In [41]:
ran_arr.shape

(10,)

In [42]:
arr.shape

(25,)

In [43]:
b = arr.reshape(5,5)

In [44]:
b.shape

(5, 5)

In [45]:
b.dtype

dtype('int64')

In [46]:
arr = np.arange(10,21)

In [47]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
arr[5]

15

In [49]:
arr[:5]

array([10, 11, 12, 13, 14])

In [50]:
arr[2:5]

array([12, 13, 14])

Broadcasting an array

In [51]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
arr[0:5] = 100

In [53]:
arr

array([100, 100, 100, 100, 100,  15,  16,  17,  18,  19,  20])

In [54]:
arr = np.arange(10,21)

In [55]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
slice_arr = arr[0:6]

In [57]:
slice_arr

array([10, 11, 12, 13, 14, 15])

In [58]:
slice_arr[:] = 99

In [59]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [60]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [61]:
arr_copy = arr.copy()

In [62]:
arr_copy

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [63]:
arr_copy[:] = 100

In [64]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [65]:
arr

array([99, 99, 99, 99, 99, 99, 16, 17, 18, 19, 20])

In [67]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [68]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[0,0]

5

In [70]:
arr_2d[1,0]

20

In [72]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [73]:
arr = np.arange(0,11)

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [76]:
b = arr > 5

In [77]:
b

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [78]:
arr[b]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [80]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [81]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [84]:
arr / arr

<ipython-input-84-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

Universal array functions

In [88]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [89]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [90]:
np.max(arr)

10

In [91]:
np.min(arr)

0

In [92]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [93]:
np.log(arr)

<ipython-input-93-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])